Import Dependencies

In [1]:
import pandas as pd
from configparser import ConfigParser

Read and Extract CSV files into DataFrames

In [2]:
covid_file = "data.csv"
covid_df = pd.read_csv(covid_file)
covid_df.head()

,ZIP Code,Week Number,Week Start,Week End,Cases - Weekly,Cases - Cumulative,Case Rate - Weekly,Case Rate - Cumulative,Tests - Weekly,Tests - Cumulative,...,Test Rate - Cumulative,Percent Tested Positive - Weekly,Percent Tested Positive - Cumulative,Deaths - Weekly,Deaths - Cumulative,Death Rate - Weekly,Death Rate - Cumulative,Population,Row ID,ZIP Code Location
0,60636,10,3/1/2020,3/7/2020,NaN,NaN,NaN,NaN,0,0,...,0.0,NaN,NaN,0,0,0.0,0.0,32203,60636-10,POINT (-87.668597 41.77599)
1,60642,15,4/5/2020,4/11/2020,8.0,32.0,40.0,158.4,47,187,...,925.7,0.2,0.2,0,0,0.0,0.0,20201,60642-15,POINT (-87.657821 41.899935)
2,60660,22,5/24/2020,5/30/2020,31.0,366.0,72.0,846.4,340,2029,...,4692.2,0.1,0.2,0,37,0.0,85.6,43242,60660-22,POINT (-87.666362 41.991062)
3,60604,15,4/5/2020,4/11/2020,NaN,NaN,NaN,NaN,1,11,...,1406.6,NaN,NaN,0,0,0.0,0.0,782,60604-15,POINT (-87.62902900000002 41.878153)
4,60654,19,5/3/2020,5/9/2020,5.0,109.0,26.0,569.6,93,505,...,2639.1,0.1,0.2,0,0,0.0,0.0,19135,60654-19,POINT (-87.63635400000001 41.892485)

Clean the data by dropping NAN

In [3]:
covid_clean = covid_df.dropna()
covid_clean.head()

,ZIP Code,Week Number,Week Start,Week End,Cases - Weekly,Cases - Cumulative,Case Rate - Weekly,Case Rate - Cumulative,Tests - Weekly,Tests - Cumulative,...,Test Rate - Cumulative,Percent Tested Positive - Weekly,Percent Tested Positive - Cumulative,Deaths - Weekly,Deaths - Cumulative,Death Rate - Weekly,Death Rate - Cumulative,Population,Row ID,ZIP Code Location
1,60642,15,4/5/2020,4/11/2020,8.0,32.0,40.0,158.4,47,187,...,925.7,0.2,0.2,0,0,0.0,0.0,20201,60642-15,POINT (-87.657821 41.899935)
2,60660,22,5/24/2020,5/30/2020,31.0,366.0,72.0,846.4,340,2029,...,4692.2,0.1,0.2,0,37,0.0,85.6,43242,60660-22,POINT (-87.666362 41.991062)
4,60654,19,5/3/2020,5/9/2020,5.0,109.0,26.0,569.6,93,505,...,2639.1,0.1,0.2,0,0,0.0,0.0,19135,60654-19,POINT (-87.63635400000001 41.892485)
5,60641,15,4/5/2020,4/11/2020,88.0,160.0,124.0,225.3,282,650,...,915.2,0.3,0.2,4,6,5.6,8.4,71023,60641-15,POINT (-87.746791 41.946682)
6,60622,23,5/31/2020,6/6/2020,13.0,538.0,25.0,1019.1,377,3217,...,6093.6,0.0,0.2,1,51,1.9,96.6,52793,60622-23,POINT (-87.681818 41.902762)

Verify data types

In [4]:
covid_clean.dtypes

ZIP Code                                 object
Week Number                               int64
Week Start                               object
Week End                                 object
Cases - Weekly                          float64
Cases - Cumulative                      float64
Case Rate - Weekly                      float64
Case Rate - Cumulative                  float64
Tests - Weekly                            int64
Tests - Cumulative                        int64
Test Rate - Weekly                        int64
Test Rate - Cumulative                  float64
Percent Tested Positive - Weekly        float64
Percent Tested Positive - Cumulative    float64
Deaths - Weekly                           int64
Deaths - Cumulative                       int64
Death Rate - Weekly                     float64
Death Rate - Cumulative                 float64
Population                                int64
Row ID                                   object
ZIP Code Location                        object
dtype: object

In [5]:
#save to a csv file
covid_clean.to_csv("Clean.csv", index=False)